### ISSUE TITLE
get motor position without hardware call

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1010]
I would like to read the last motor positions without doing any hardware calls.
Assuming I did a %wu in advance I would like to access the results of this last call.
So is there a way to do that? Everything I found using the motor API or Tango Proxy allways triggers a ReadOne() call of the motor and hence a hardware call, which I would like to avoid. The motor is implemented directly in Sardana without an additional Tango layer.

In SPEC all motor and counter stored in an simple array and can be accessed from anywhere anytime.

Best

Daniel

**Comment by reszelaz** [comment]
You can use the Taurus extension [`Motor`](https://sardana-controls.org/devel/api/sardana/taurus/core/tango/sardana/pool.html#sardana.taurus.core.tango.sardana.pool.Motor) class to do that.
For example in the macro code:
```python
mot = self.getMotor("mot01")                                                
pos = mot.getPosition()
```
To force the readout you simple use the `mot.getPosition(force=True)`

**Comment by dschick** [comment]
thanks, I thought I tried that already, anyway.
Is it possible to use that also from within a counter?

**Comment by dschick** [comment]
now I am using

proxy = taurus.Attribute('tango://tesla:10000/motor/kepcoctrl/0/position')
val = proxy.read().value

this does not call the hardware to get the motor position, but also does not update the value on change of the motor.

So this here works from within spock
```

proxy = Attribute('tango://tesla:10000/motor/kepcoctrl/0/position')
print(proxy.read().value)
%mv kepco -0.1
print(proxy.read().value)
%mv kepco 0.1
print(proxy.read().value)

0.0977
-0.0977
0.0977

```

But when I do the read.value from the same Taurus Attribute Proxy from within a PseudoCounter two times and change the position of the motor in between, the value only gets updated/changed, if the integration time is approx. larger than 2s.

Is there a way to change the update rate of the Taurus Proxy?
And why is it updating itself when working from within spock?

**Comment by reszelaz** [comment]
> Is it possible to use that also from within a counter?

Yes, within a macro you can do:
```python
ct = self.getCounterTimer("ct01")
ct.getValue()
```

**Comment by dschick** [comment]
> > Is it possible to use that also from within a counter?
> 
> Yes, within a macro you can do:
> 
> ```python
> ct = self.getCounterTimer("ct01")
> ct.getValue()
> ```

I meant, reading the motor from with the code of a counter, but thanks for the snippet

**Comment by reszelaz** [comment]
> I meant, reading the motor from with the code of a counter, but thanks for the snippet

Sorry I read too quickly your question.

To use the Taurus extension within a pseudo counter (or any other python application) you would need to first register it.
All the Pool elements extensions can be registered with this single call:

```python
from sardana.taurus.core.tango.sardana.pool import registerExtensions
registerExtensions()
```

Then you simply use taurus. The trick is that the Pool element devices that you obtain, from the moment of registration on, are enriched by the extra API present in the extension:

```python
mot = taurus.Device("mot21")
mot.getPosition()
```

Be aware that a registration of the extension in one controller will affect the whole Pool, I mean the rest of the controllers. In principle this should not be a problem since the extension classes still provides the API of the standard `taurus.core.tango.TangoDevice`. But if you decide to try it (personally I have not used the extension in the Pool controllers), just let us know how did it go.

Regarding the pure taurus classes (the snipped that you posted) there is a kind of caching mechanism with an invalidation period. I will need to review it before writing anything about it:)

**Comment by cpascual** [comment]
Just jumping in to add some info related to [the following specific question from @dschick](https://github.com/sardana-org/sardana/issues/1010#issuecomment-453043230) :

>But when I do the read.value from the same Taurus Attribute Proxy from within a PseudoCounter two times and change the position of the motor in between, the value only gets updated/changed, if the integration time is approx. larger than 2s.

I think that the key to understand this is that when you do `proxy.read().value`, you are doing implicitely a *cached* read, **but** the cache has an expiration time equal to the polling period (i.e., taurus will return the cached value only if the cache is newer than polling period, which by default is set to 3s; otherwise it forces a re-read anyway)

> Is there a way to change the update rate of the Taurus Proxy?

You can adjust the polling period at attribute level with `TaurusAttribute.changePollingPeriod()` or for all the application using `taurus.changeDefaultPollingPeriod()`

**Comment by dschick** [comment]
Dear @cpascual and @reszelaz I tried both of your two options and both basically work, whereas the use of the extra API is not generating any extra call to the hardware, which is why I am using this now.
Till now I did not notice any problems using the extensions.

Thanks again

**Comment by reszelaz** [comment]
> You can adjust the polling period at attribute level with TaurusAttribute.changePollingPeriod().

Since I just needed to do it in one pseudo motor controller, I just complement this issue with a code snippet:

```python
import time

import taurus

def cb(*args):
    pass

attr = taurus.Attribute("mot01/position")  # executes one HW read
attr.changePollingPeriod(float("inf"))
attr.addListener(cb)  # executes one HW read
print(attr.read().value)  # no HW read
time.sleep(5)
print(attr.read().value)  # no HW read
time.sleep(5)
print(attr.read().value)  # no HW read
time.sleep(5)
print(attr.read().value)  # no HW read
time.sleep(5)
print(attr.read().value)  # no HW read
```
