### ISSUE TITLE
empty Trend1D after upgrade of Sardana

### ISSUE THREAD

**Issue by kklmn** [sardana-org/sardana#1017]
Hi,

After upgrade to Taurus 4.4.0 and Sardana 2.5.0 we don't have Trend1D plots for Sardana scans.
I posted it to Taurus issues (https://github.com/taurus-org/taurus/issues/841), Carlos P suggested to move it here.

In meantime we have discovered that re-creation of measurement groups has solved the issue.

Whether this behavior is intended/expected or not, maybe there should be a messagebox that suggests to make all measurement groups anew?

**Comment by reszelaz** [comment]
This is certainly a bug. I can take a look on that today. I suspect that these may come from the MG configuration refactoring done in SEP18.

**Comment by reszelaz** [comment]
> I suspect that these may come from the MG configuration refactoring done in SEP18.

After reading carefully the original report this can not be due to the SEP18 changes cause these were integrated after 2.5.0.

I have just checked creating the measurement group configuration (plot configuration) on sardana 2.4.0 and latest taurus develop (4.5.0-alpha) and later upgrade to sardana 2.5.0 while maintaining the same version of taurus and I was not able to reproduce the problem.

@kklmn could you please post the the exact versions of taurus and sardana from which you upgraded to sardana 2.5.0 and taurus 4.4.0? I will continue this investigation tomorrow.
