### ISSUE TITLE
pool motor widget limits gets activated without any reason (SF#178)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#111]
This mysterious behavior happens while moving a motor. 
The +/- limits buttons gets activated without any reason.

It seems to be related with the software versions:
It was not present with Tango 7.2.6 but happens with Tango 8.1.2.
I'm not able to reproduce it with PyQt 4.8.5 but with PyQt 4.4.3 yes.

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/178](https://sourceforge.net/p/sardana/tickets/178)

**Comment by reszelaz** [comment]
The patch from the previous comment was about another issue.

This issue still persist what was shown in the Jan18 release tests in https://github.com/sardana-org/sardana/pull/711#issuecomment-369855509. According to https://github.com/taurus-org/taurus/issues/107 it is caused by a specific combination of nympy & PyTango dependency. The strategy in Taurus was to close the issue as _wontfix_ so I do the same is case of Sardana.
