### ISSUE TITLE
Scan online trend widget

### ISSUE THREAD

**Issue by reszelaz** [sardana-org/sardana#1178]
As you know from https://github.com/sardana-org/sardana/pull/1173#issuecomment-516479373 we won't be able to reuse the current *online scan trend*, implemented with `TarusuTrend` and `Qwt5`.

I wonder if someone already made some alternative widgets, maybe using directly `pyqtgraph`, or some other library for online scan plotting?

Could you please post here your sollution. Many thanks in advance!

**Comment by reszelaz** [comment]
I recall from the last Sardana Workshop at DESY that Tim was working on some scan plotting widget using silx. @schooft could you give us more details, please?

**Comment by schooft** [comment]
I do use the silx plot widgets in my applications for displaying detector images and analyzed 1D data. However, there is no direct integration with Sardana or Taurus in the current state of development.

The silx widgets provide all the features I need and are quite fast when using the OpenGL backend. Additionally, they are well documented and have a large test suite. Unfortunately, I never used TaurusPlot or PyQtGraph, so that I cannot comment on the differences and how difficult it would be to replace Qwt with silx in Taurus.

**Comment by reszelaz** [comment]
Thanks for the answer @schooft!

So you are just plotting the scan result of 1D and 2D, and you just refresh the last acquired frame - you don't produce a trend (evolution) of the scan. Also you are directly displaying the data produced by the detectors in the file system - there is no Tango subscription to the `RecordData` attribute of the door.

Currently we are evaluating to the plotting library, we are more inclined into the pyqtgraph, but silx is still an option. Anyone has a preference?

Anyone else has made some other scan plotting solutions?

**Comment by reszelaz** [comment]
@tiagocoutinho already implemented a minimal solution using pyqtgraph: https://github.com/reszelaz/sardana/pull/25. For the moment let's close this issue. At any time we can reopen it and come back to this discussion.
