### ISSUE TITLE
Missing 2.8.4 version on PyPI

### ISSUE THREAD

**Issue by stanislaw55** [sardana-org/sardana#1253]
Hello Sardana community
in this repository, there's tag and release with number 2.8.4 but latest available version from PyPI is 2.8.3. Is this intended?

This issue is similar to #1204 

Thanks in advance

**Comment by reszelaz** [comment]
Hi Stanislaw,
Up to now we were not uploading the hotfix releases to PyPI. We can add it to the [hotfix procedure](https://github.com/sardana-org/sardana/wiki/How-to-Hotfix-Sardana) if there is an interest in it. And of course upload this one now since I assume you need it. Meanwhile you can also install with pip from a github tag.
Cheers!

**Comment by stanislaw55** [comment]
Hi @reszelaz 
thanks for rapid response!
Right now I do not need this version of Sardana. I just wanted to point this out since it could just slip in the middle of development of Sardana 3.0.0

**Comment by reszelaz** [comment]
We are now using the GitHub workflows to deploy to PyPI. So the situation of not having a hotfix release on PyPI should not repeat. Cheers!
