### ISSUE TITLE
change of TwoDExpChannel image/array size

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#1296]
Hi all,

we have implemented a TwoDExpChannel based on a Tango CDD Device Server.
(Btw. SEP2 and SEP18 are really great enhancements of the API!)
Currently, we can change the image size of the CCD in the TANGO DS via cropping and binning.

When initially adding the 2D image of the TwoDExpChannel to one of our measurement groups, the size of the 2D array will be automatically recognized.
However, when we change the size of the image array due to cropping or binning the next acquisition via the measurement will result in an error, due to the wrong image size.

Are there ways to autmatically update the size of the image to always the size of the image attribute of the underlying TangoDS?

Best

Daniel

**Comment by reszelaz** [comment]
Hi Daniel,
Sorry for late answer!
We were aware of this lack of user friendliness when working on SEP2. I think we could retake this topic now.
Talking a little bit from memory, I think that this information (shape) is mainly used by the recorders? And in the case of the H5 recorder it is used to define the shape of the datasets.
If this is true, then we could evaluate these two options:

1. We want to allow scans in which experimental channels change the shape of the data during the scan. I personally don't know a use case for that, but maybe someone has? Then the shape could be understood as the maximum shape and should be maintained in the channel configuration (expconf). 
2. We assume that in all scan points the data shape won't change. In this case, we could postpone the dataset creation till the moment of receiving the first value by the recorder. Then we could eliminate the shape from the channel configuration (expconf).

Regarding point 1 maybe there are even some ways of re-shaping datasets a posteriori. Well there is one - we use it for the _scan points_ dimension, but I don't know if we could have a dataset without defining any dimension at all.

**Comment by dschick** [comment]
hi Zibi,

I agree that 2. is the most common scenario. So it would be great if the recorder could adapt to the data source size after the first acquisiton of a scan.

Honestly, we are not chaning the image size too often, but for especially for unexperienced users it is a bit confusing, when an error message in sardana appears, when they change the binning of the detector.

Best

Daniel

**Comment by reszelaz** [comment]
I think that delaying the shape determination until the first data arrives to the recorder won't be so easy. Yes, we could do it for the H5 recorder, but I reviewed the recorders that we have in Sardana and most of them use the shape information already in the `_startRecordList`. For example H5 do it to create the dataset, JSON do it to skip 1D and 2D channels from serialization, SPS to call sps.create(), FIO to organize channels in CT and MCA groups, SPEC to place MCA shape in the scan header, etc..
So, there are recorders which need this information when starting the record list and delaying the dataset creation in the case of H5 would be just a workaround.

This _shape_ expconf configuration is very related to the 1D/2D configuration e.g. binning/ROI that we excluded from the SEP2 on purpose to reduce its scope. Let's strat thinking if we could solve this issue without opening another big SEP... AFAIK the shape can change either when we change the detector's binning, ROI or rotate the image. There is need to allow the users adjust all this parameters: binning, ROI, ... which could be considered as part of measurement group configuration (of course it would need to exist as well on the experimental channel level for independent acquistions). But shape is more a result of the configuration and not the configuration itself. I have checked how this is solved in the case of the LIMA library. From what I saw in the documentation they use `image_bin` and `iamge_roi` (read and write) and `image_width` and `image_height` (read only).

Based on this reasoning and the LIMA example I propose that we eliminate the _shape_ from the expconf configuration and provide shape on the experimental channel level as read only attribute(s).
Here we have two options:
* two separate scalar attributes `width` and `hight` for 2D and one attribute `width` (or `length`) for 1D
* only one attribute spectrum attribute `shape` which could either have two elements (2D) or 1 element (1D)

The controller (plugin) would then provide these values with, for example, the `GetAxisPar` method.

The GSF could then read them and pass the result to the recorders so they know the shape already in the `_startRecordList`. Ideally this readout and then calls to the `_startRecordList` should take place after executing the measurement group's `Prepare` command. Currently the `_startRecrodList` are called before the measurement group's `Prepare` command execution. But since we still don't have any experiment configuration in Sardana which could affect the shape for the moment I don't see it absolutelly mandatory to refactor the GSF to invert this order.

In conclussion, I think we don't need wait for the 1D/2D configuration SEP - IMO shape is not configurable but a result of the configuration.
I would not maintain backwards compatibility and try to include it in Sardana 3 release (implementation should be very small). IMO if someone was using 1D/2D experimental channels he must had faced this lack of user friendliness, and will appreciate that by implementing the `GetAxiPar` in the controller all the problem disappears.

What is your opinion about all that? If you agree, also vote between the attribute(s) name options:) Many thanks!

**Comment by guifrecuni** [comment]
I'd vote for the second option:

> only one attribute spectrum attribute `shape` which could either have two elements (2D) or 1 element (1D)

**Comment by teresanunez** [comment]
Hi Zibi,
             about the names, I don't have a clear opinion, perhaps also the second one.
My question is about the backwards compatibility of the controllers, we have many 1D and
2D controllers, should I have to change all of them, or is it possible to make the implementation
 so that if the controller do not provide this information it will behave as before?. Thanks a lot.

**Comment by reszelaz** [comment]
Hi Teresa,

First of all, let's review how the shape information was filled in the measurement group configuration.
When 1D/2D channel was added to the measurement group in the `expconf` its Value attribute was read and its shape was used in the configuration. Then it was never updated automatically - one had to update it if the shape had changed. The `defmeas` macro was never filling the shape information.

I think I imagine your case. You were using 1D and 2D channels but you were not hitting this issue. Either because:
* you were creating measurement groups with the correct shape information using your XML tool to create Sardana
* you were never changing binning/ROI - things which affects the shape
* you were not using recorders which needs precise shape information e.g. `FIO_FileRecorder` just needs to know the shape to determine if the channel is 1D or 2D but not if the image shape is 1024x1024 or 2048x2048

Please confirm which of the above scenarios describe you case? Or if none of them then describe it yourself.

One possibility to provide backwards compatibility would be to read the value whenever read of the shape does not work (is not implemented). For 2D something like this (it is very simplified):

```python
    def read_shape(self):
        shape = self.controller.get_axis_par(self.axis, "shape")
        valid_shape = False
        try:
            if len(shape) == 2:
                valid_shape = True
        except TypeError:
            pass
        if not valid_shape:
            shape = numpy.array(self.value).shape        
        return shape
```

So, it is using the same principle that Sardana uses now with the `expconf`. The difference is that it reads the shape once per scan and not only when the channel is added to the measurement group. Would this work for you? Note that I would not treat it is permanent solution and remove it from Sardana as soon as the backwards compatibility is not needed - it is not compatible with SEP17.

**Comment by teresanunez** [comment]
Hi Zibi, thanks for the reply. We are not changing the shape of the attribute,this is the reason.
The solution you propose is fine, thanks.

**Comment by dschick** [comment]
Hi @reszelaz,

I would like to come back to this issue. Currently we would like to bypass the automatic shape determination by setting the shape within our macros, which also set the ROIs of the camera.

However, I am not able to find a method to set or get the shape of a channel in the current measurement-group API.

Best

Daniel

**Comment by reszelaz** [comment]
Hi Daniel,

> However, I am not able to find a method to set or get the shape of a channel in the current measurement-group API.

It was not introduced on purpose cause we knew it was going to be removed. 

I just reviewed this issue and I see that my optimistic plan was to have it for Sardana v3, but we did not get there. I think it is not a big effort to implement it. 
If we do it would you be willing to take care for the PR review and tests?

Many thanks!

**Comment by dschick** [comment]
sure, I can do the review!

Many thanks

**Comment by reszelaz** [comment]
#1466 got merged and will be availablem in Jan21 release. I'm closing this issue.
Many thanks to all for your comments and contributions.
