### ISSUE TITLE
polling an attribute from a macro

### ISSUE THREAD

**Issue by marouanebj** [sardana-org/sardana#1322]
Hello,

In my code a QtGui I'm using a ZeroDExpChannel as model:
in spock it is zdild1320
```
Door_ipadiffx_1 [1]: zdild1320
	Result [1]: ZeroDExpChannel(expchan/ild1320zdctrl/1)
```
In my QWidget I use a Timer (see here after) because in some situations the attributes may change without any intervention. 
```python
class LaserDistanceWidget(Qt.QWidget):
    def __init__(self, parent, label, model, unit):
        Qt.QWidget.__init__(self, parent)
        ...
        self.acquisitionTaurusLed = TaurusLed(self)
        self.acquisitionTaurusLed.setModel(model + "/laseractive")
       ...
        self.displayUpdateTimer = Qt.QTimer(self)
        self.displayUpdateTimer.timeout.connect(self.onDisplayUpdateTimerTimeout)
        self.displayUpdateTimer.start(300)

    def onDisplayUpdateTimerTimeout(self):
        device = taurushelper.Device(self.model)
        deviceState = device.getChildObj("/state")
        deviceStatus = device.getChildObj("/status")
        deviceCurrentValue = device.getChildObj("/currentValue")
        deviceState.poll()
        deviceStatus.poll()
        deviceCurrentValue.poll()
        # extra
        laserZD = device.getChildObj("/laseractive")
        laserZD.poll()
```
Now I say the will not change without "intervention", except I have a macro that for examples sets the laseractive attribute. Can I from that macro (assuming that in the LaserDistanceWidget I remove the onDisplayUpdateTimerTimeout method) poll the state and status so they gets updated in the GUI ?
If yes can you tell me how ?
Here is what I did: 
```
class setLaserActive(Macro):
    """This macro set the laseractive attribute of the ExpChannel.
    """

    param_def = [ ['expChannel', Type.ExpChannel, None, 'expChannel'],
                  ['value', Type.Boolean, None, 'the new value'],
                ]

    def run(self, expChannel, value):
        expChannelDevice = self.getDevice(expChannel.getName())
        self.output("expChannel.dev_name = " + str(expChannel))
        laseractiveAttr = expChannelDevice.getChildObj("/laseractive")
        self.output("laseractiveAttr = " + str(laseractiveAttr))
        laseractiveAttr.write(value)
        self.output("value = " + str(value))
        # laseractiveAttr.poll()
        time.sleep(1)
        stateAttr = expChannelDevice.getChildObj("/state")
        statusAttr = expChannelDevice.getChildObj("/status")
        stateAttr.poll()
        statusAttr.poll()
```
The laseractive (even  with the poll() commented in the macro) gets updated on the GUI,
But Not the state or the status.
I think I might have misunderstood the poll(), can you explain it rapidly.
Thanks,

**Comment by marouanebj** [comment]
Hi again, I put this here too because for me it is a bit the same subject.
In spock I have my ZeroDExpChannel:
```
Door_ipadiffx_1 [1]: zdild1320
	Result [1]: ZeroDExpChannel(expchan/ild1320zdctrl/1)
```
And I did that
`Door_ipadiffx_1 [1]: zdild1320.poll_attribute("laserActive", 50)`
I did not understand what it does, if you can explain rapidly? Thanks.
But Is this setting saved someware on the tangoDB ?
Is it still acting when I restart spock ?
Is it still acting when I restart the sardana server ?
If Yes how to set it to its default behavior ?
Thanks

**Comment by reszelaz** [comment]
Hi Marouane,

You reached a very interesting and at the same a hard to explain point in the Sardana world - polling. I will try to clarify it.
Sardana has a client-server architecture. Sardana reuses the client-server communication protocol from the Tango control system framework (actually Sardana reuses more Tango features). Sardana also uses Taurus - a library for building client applications. Taurus was originally meant to be the library for building Tango user interfaces in Python. And here comes the complexity - both Tango and Taurus comes with the polling mechanisms. Both poll the attributes but there is crucial difference between them. Tango polls directly in the server (there is a polling thread in the server process which reads the attribute at a given frequency) and Taurus polls in the client since this is the only way he can poll - Taurus is a client.
Tango does basically two things when polling: fills the polling buffer with the newly read values (so the next client readout can use the value from the buffer) and eventually pushes an event with the newly read value if this one fullfills the event criteria. You can find more one the Tango polling in its [documentation](https://tango-controls.readthedocs.io/en/latest/development/device-api/device-polling.html#device-polling).
Taurus has a polling thread in the client process (could be your GUI) and reads the value using the Tango protocol from the server. Then it communicates (within the same process) these new values to all the widgets visualizing this attribute (model) with the Qt signals.

I would not recommend using Sardana with the Tango polling, at least at the beginning of your journey with Tango. First, you should be able to achive most of the things with the Taurus polling. Second, we have found some issues when using Tango polling with some Sardana attributes (the ones which participate in the operations like motion - position, state and status or acquisition - value, state and status).

From your examples/questions I see that you use [`TangoAttribute.poll`](http://taurus-scada.org/devel/api/taurus/core/tango/_TangoAttribute.html#taurus.core.tango.TangoAttribute.poll) method. I think you don't need to use it. Actually the case that you describe - attribute changes value without user interaction, we also found in the [PoolMotorTaurusValue](https://sardana-controls.org/users/taurus/poolmotortv.html) widget. There the position attribute, which emits events while the motor moves, may also change without user interaction - motors cross talk, fluctuating encoder, or manual manipulation of the axis. Hence in the said widget we additionally enable polling for the position using the [`TaurusAttribute.enablePolling`](http://taurus-scada.org/devel/api/taurus/core/_TaurusAttribute.html#taurus.core.TaurusAttribute.enablePolling). And I would recommend you doing the same, but only in the case when the attribute may change without user interaction and it pushes events e.g. position, value, state, status. Otherwise Taurus will enable the polling for you. Note that you can also modify the default polling period of 3 s. Using this solution you won't need a QTimer (taurus will start and manage a polling thread) neither enable any polling in the macro.

From your examples/questions I also see that you discovered the `DeviceProxy.poll_attribute` method. This one corresponds to the Tango polling. And as previously mentioned I would discorage its usage (at least knowing your current needs). And yes, it configures the polling in the Tango DB and is this configuration is persistent - applies also after the server restart. You can disable it, either programmatically: `DeviceProxy.stop_poll_attribute` or using the Jive application (comes with Tango-Java part).

Sorry for so long message. Hopefully I clarified something:)

**Comment by reszelaz** [comment]
Just a comment, you can use the following API:
```python
from taurus import Device, Attribute

device = Device("MyZeroD")
attribute = device.getAttribute("CurrentValue")
# or
attribute = Attribute("MyZeroD/CurrentValue")
```

**Comment by marouanebj** [comment]
finally I did this, (for reminder model is ZeroDExpChannel to force the polling.

```python
        modelTaurusDevice = Device(self.model)
        stateTaurusAttribute = modelTaurusDevice.getAttribute("State")
        statusTaurusAttribute = modelTaurusDevice.getAttribute("Status")
        currentValueTaurusAttribute = modelTaurusDevice.getAttribute("CurrentValue")
        stateTaurusAttribute.activatePolling(300, False, True)
        statusTaurusAttribute.activatePolling(300, False, True)
        currentValueTaurusAttribute.activatePolling(300, False, True)
```
Yes I had to force, it is because I did not manage to start properly the measurement group acquisition as you proposed in: https://github.com/taurus-org/taurus/issues/1099
you propose to use and I used my ZeroDExpCahnnel
> defmeas mntgrp02 ct01 zerod01 and run a ct macro e.g. ct 1 mntgrp02.
in spock I did that:
`defmeas mntgrp02 ct01 zdild1320
`
but I had to use ct01 so "load" the sar_demo. I still need to understand that but for now I stay with this solution.
Thanks

**Comment by reszelaz** [comment]
For your problem with measurement group acquisition can you try the following and paste here the output:

```
Door_zreszela_1 [1]: lsmeas
  Active         Name   Timer Experim. channels              
 -------- ----------- ------- -------------------------------              
             mntgrp01    ct01 ct01, ct02, ct03, ct04                 

Door_zreszela_1 [2]: lsct
   Name           Type   Controller   Axis
 ------ -------------- ------------ ------
   ct01   CTExpChannel     ctctrl01      1
   ct02   CTExpChannel     ctctrl01      2
   ct03   CTExpChannel     ctctrl01      3
   ct04   CTExpChannel     ctctrl01      4
   ct05   CTExpChannel     ctctrl01      5
   
Door_zreszela_1 [3]: ls0d
      Name              Type    Controller   Axis
 --------- ----------------- ------------- ------
   zerod01   ZeroDExpChannel   zerodctrl01      1
   zerod02   ZeroDExpChannel   zerodctrl01      2
   zerod03   ZeroDExpChannel   zerodctrl01      3
   zerod04   ZeroDExpChannel   zerodctrl01      4

Door_zreszela_1 [4]: defmeas mntgrp02 ct01 zerod01
Created mntgrp02

Door_zreszela_1 [5]: ct 1 mntgrp02
Mon Apr 20 19:23:56 2020

     ct01  =         1.0
  zerod01  =  100.16930902262314
```
Remember to:
* in `defmeas` use measurement group name which is not used yet (in my case `mntgro02`)
* in `defmeas` use dummy counter/timer as the first element in the measurement group (in my case `ct01`)
* in `ct` use measurement group that you just created (in my case `mntgrp02`)

**Comment by marouanebj** [comment]
Hi,

I worked again on this topic.
I managed to use the DummyCounterTimerController, with my 0DController and created a mntgrp
```
Door_ipadiffx_1 [27]: lsct
   Name           Type    Controller   Axis
 ------ -------------- ------------- ------
   ct01   CTExpChannel   dummyctctrl      1

Door_ipadiffx_1 [28]: ls0d
          Name              Type      Controller   Axis
 ------------- ----------------- --------------- ------
     zdild1320   ZeroDExpChannel   ild1320zdctrl      1

Door_ipadiffx_1 [29]: lsmeas
  Active             Name   Timer Experim. channels  
 -------- --------------- ------- -------------------
            mntgrpild1320    ct01 ct01, zdild1320  
```

Your example work:
```
Door_ipadiffx_1 [36]: ct 1 mntgrpild1320
Mon Oct 19 17:25:42 2020

       ct01  =         1.0
  zdild1320  =      4750.0
```

Q1/ I  also used it calling mntgrpild1320.start() and then mntgrpild1320.stop()
what I see is that it 'stops' after the integrationtime is finished, is it possible to have a infinite integrationtime ?

Q2/ My zdild1320 is a Lazer distance measure.
when I stop it I set laserActive attribute to False:
```
    def StopOne(self, ind):
        # self._log.debug("====>>>> FakeZeroDController StopOne START ind=" + str(ind) + "<<<<<<====")
        self.SetAxisExtraPar(ind, "laserActive", False)
```
And I see that when I call `mntgrpild1320.stop()` it calls `zdild1320.stop()` and that's good for me.
I created in zdild1320 controller a `StartOne(self, ind)` to switch on the laserActive but when I call mntgrpild1320.start() it is not called. Is there a method inside zdild1320 that is called when I do mntgrpild1320.start() ?

Thanks.

**Comment by reszelaz** [comment]
> I managed to use the DummyCounterTimerController, with my 0DController and created a mntgrp

Great!

> Q1/ I also used it calling mntgrpild1320.start() and then mntgrpild1320.stop()
> what I see is that it 'stops' after the integrationtime is finished, is it possible to have a infinite integrationtime ?

No, it is currently not possible. But IMO this use case has some sense, especially with the 0D experimental channels. We could discuss in a separate issue on it.

> Q2/ My zdild1320 is a Lazer distance measure.
> when I stop it I set laserActive attribute to False:
> 
> ```
>     def StopOne(self, ind):
>         # self._log.debug("====>>>> FakeZeroDController StopOne START ind=" + str(ind) + "<<<<<<====")
>         self.SetAxisExtraPar(ind, "laserActive", False)
> ```
> 
> And I see that when I call `mntgrpild1320.stop()` it calls `zdild1320.stop()` and that's good for me.

Yes, I just reviewed the code and the 0D controllers implement _Stoppable_ interface.

> I created in zdild1320 controller a `StartOne(self, ind)` to switch on the laserActive but when I call mntgrpild1320.start() it is not called. Is there a method inside zdild1320 that is called when I do mntgrpild1320.start() ?

... but not the _Startable_ interface. I think we should review the reasons for this.

I have a question on your hardware. The laser and the detector both form the same equipment right? And are controlled from the same hardware controller?

Just for the reference I post here links to your initial [question](https://sourceforge.net/p/sardana/mailman/message/36928524/) and my [answer](https://sourceforge.net/p/sardana/mailman/message/36930907/) on the sardana devel maining list.

Also, another question, how to you plan to make the readouts every 1 s? Do you plan to use `timescan` for that?

**Comment by marouanebj** [comment]
Hi,
 
> I have a question on your hardware. The laser and the detector both form the same equipment right? And are controlled from the same hardware controller?

Yes It is the same Hardware 

> Just for the reference I post here links to your initial [question](https://sourceforge.net/p/sardana/mailman/message/36928524/) and my [answer](https://sourceforge.net/p/sardana/mailman/message/36930907/) on the sardana devel maining list.
>
> Also, another question, how to you plan to make the readouts every 1 s? Do you plan to use `timescan` for that?

Thanks for the link to remember the story. For the readouts every 1s I did not really though on how to do that.
I'll tell you when I'm back on the subject.

**Comment by reszelaz** [comment]
> > I have a question on your hardware. The laser and the detector both form the same equipment right? And are controlled from the same hardware controller?
> 
> Yes It is the same Hardware

In this case I think it has a lot of sense that we extend the `ZeroDController` with the methods that would allow more control (in your case power on and off of the laser) e.g. _start_, _prepare_ and _cleanup_ methods.

The concept of _cleanup_ methods does not exist yet in Sardana but I think in some occassions it may have sense to release some resources when the measurement has finished and not be obliged to discover the end of measurement in the controller e.g. base on the state change.
