### ISSUE TITLE
How to force in PoolMotorTV widget the motor movement between abosulte or relative

### ISSUE THREAD

**Issue by mbroseta** [sardana-org/sardana#1406]
Hello,

We are using PoolMotorTV widget in our GUI's. This widget includes another widget to select between motor movement using absolute or relative position. The user can select and option and its selection is stored in the Taurus config file for the next time the widget will be open. But we would to disable and hide this selection for the user, and fix always one type of movement.

How can I do this using this widget?

Regards
Manolo.

**Comment by reszelaz** [comment]
Hi Manolo,
I'm affraid that currently it is not possible. However this feature has a lot of sense in my opinion.
Are you interested in progammatic or graphical interface to pre-select the motion mode?

For the progamatic one this could be something like this:

```python

class MotionMode(IntEnum):
  Selectable = 0
  Absolute = 1
  Relative = 2
  
class PoolMotorTV:

...
  def setMotionMode(self, mode):
    ...
....

# and in you client application
panel = TaurusForm()
panel.setModel(["mot01"])
panel[0].setMotionMode(MotionMode.Absolute)
```

For the graphical one this could be added to the context menu, next to the _expert mode_ or _compact mode_.

**Comment by HEnquist** [comment]
The suggested approach from @reszelaz would be easy, but why only for the absolute/relative mode? Selectively hiding all unwanted options clutters the interface.
Better to implement as new widget ans use the TaurusForm ItemFactory plugin mechanism to register it.

**Comment by HEnquist** [comment]
@reszelaz do you agree with this? If not, please remove the "wontfix" label.

**Comment by reszelaz** [comment]
> Better to implement as new widget ans use the TaurusForm ItemFactory plugin mechanism to register it.

That should also work, and is already available. I agree to close this issue. Since @mbroseta does not work at ALBA anymore, I will pass this info to the group that continues his work.

The only thing which is different between these two approaches is, AFAIK, that with the item factory it won't be possible to have two different widgets for the same model in the GUI e.g. one widget for the absolute move and another for the relative move. But  I'm not aware of anyone needing this.
