### ISSUE TITLE
sardana motors integration at HDB++

### ISSUE THREAD

**Issue by aureocarneiro** [sardana-org/sardana#1429]
Hi Sardana,
 
At MAX IV, we want to archive some motors position and we use HDB++. In summary we have two options (which I can imagine):

1- Enable polling to the motors.
2- Use event based.
 
Some comments:
 
1- Some people in our group reported the polling config can conflict with sardana acquisition. The tango polling threads can became overloaded based in the amount of polled attributes, we will need to increase the number of polling threads. 
2- The motors doesn't send events when stopped, only during the motion. The motors also send the change event on the position before they really stop moving. After they "stop", they still continue trying to move a little closer to the target position. 
 
What is your solution at other facilities ? Can you recommend something for us ?
 
Henrik, has an idea to make a "motor position subscriber" that listens to events and also reads the position periodically in between.

 
Cheers,

/Aureo

**Comment by reszelaz** [comment]
Hi Aureo,

I will reverse the order of the questions, so first:

> What is your solution at other facilities ? Can you recommend something for us ?

I had just a brief chat with @sergirubio, and this is what we do at ALBA:
* we don't use the _Tango archive events_, according to Sergi, these loads the CPU too much
* we do use the _Tango change events_, (these are pushed by the Pool while motors are moving) and subscribe to them from the `HdbEventSubscriber` after prior setting the class property `SubscribeChangeAsFallback=True`.
* we use a dedicated device class `PyHdbppPeridicArchiving` run in a separate Tango DS for the periodic archiving e.g. while the motors are not moving. This device class is currently only in the internal ALBA repository, but I think that we could move it to some public repo if you would like to take a look on it.

I have also reviewd some old discussion: #456, and I can see that Solaris was using the HDB++ with archive events and polling and they managed to make it work withe the motors from Pool. @cpt-majkel is it still the case that you use it this way?

Now your two points:
> 1- Some people in our group reported the polling config can conflict with sardana acquisition. The tango polling threads can became overloaded based in the amount of polled attributes, we will need to increase the number of polling threads.

Even we at ALBA had discovered problems with the polling. These were however never deeply investigated due to the lack of time. I have just moved here a litttle bit old _one-time_ issue from our internal issue tracker - #1431. This is the only documented issue that I'm aware of. Could you do the same with your experiences? If it is related to motion, plese complement this recently created issue. If it affects acqusition, as you mention, I would open a dedicated issue for that. Let's see if we can find any conlussions on where the root cause is?

> 2- The motors doesn't send events when stopped, only during the motion. The motors also send the change event on the position before they really stop moving. After they "stop", they still continue trying to move a little closer to the target position.

Exactly, the change events are only pushed while the motion is controlled by Sardana, and this includes the intermediate events while the motion is still in progress. The frequency of events will depend on the change criteria Tango configuration. I'm not aware of the issue that you point here: "After they "stop", they still continue trying to move a little closer to the target position." It sounds to me like a bug. Could you elaborate it more, maybe as a separate issue?

Now, regarding sending the events while Sardana does not control motion, there is one option to be evaluated. In Sardana, there is some old code which is not really used: 

https://github.com/sardana-org/sardana/blob/7561d63639cd2088e5e455a579c0d028edde3c70/src/sardana/pool/poolmonitor.py#L42

It was planned for upading the clients with the state change events of all the elements belonging to a Pool. This solution could be evaluated for the archiving purposes also. It would have an advantage over Tango or external polling cause it can take a benefit of multi axes queries to the controllers e.g. ask all the IcePAP motors states/positions with one query to the hardware. But we would need to carefylly evaluate this. If you think it is interesting let's call a dedicated design meeting.

And finally:

> Henrik, has an idea to make a "motor position subscriber" that listens to events and also reads the position periodically in between.

Nice! But before, maybe it is worth to take a look on the `PyHdbppPeridicArchiving`?

**Comment by cpt-majkel** [comment]
Hi all,

Some time ago we have also experienced issues with Tango polling set on Sardana devices (Pool elements in particular). 

At the moment our solution for this problem is to use some dummy `FacadeDevice`  with `proxy attribute` on motor position. Then we use archive events and polling on this facade. 

Cheers,
Michal

**Comment by reszelaz** [comment]
Thanks for the feedback Michal!

> Some time ago we have also experienced issues with Tango polling set on Sardana devices (Pool elements in particular).

Do you think you could still recover some information on these issues and post it in #1431?

**Comment by cpt-majkel** [comment]
Sure, i'll talk with @daneos because AFAIK he was the one who investigated this issue. When I find out something, I will post it there.

**Comment by reszelaz** [comment]
These are the projects that we use for period archiving at ALBA:

https://github.com/ALBA-Synchrotron/PyHdbppPeriodicArchiver
https://github.com/ALBA-Synchrotron/libhdbppinsert

Thanks @sergirubio for sharing them!

**Comment by reszelaz** [comment]
Hi @aureocarneiro,
I was just reviewing all question issues. I wonder if go should keep this issue in the backlog? Or maybe we could close it?
Many thanks!

**Comment by johanfforsberg** [comment]
I think it can be closed, we are testing a facade based solution now. But maybe there's some info in this ticket that could be useful for someone else.

**Comment by aureocarneiro** [comment]
Yes we can close :)
