### ISSUE TITLE
Cannot recreate measurement group with same name

### ISSUE THREAD

**Issue by tiagocoutinho** [sardana-org/sardana#1528]
Hi,
Steps:
1. create a measurement group `mg1` with a channel `c1`: `defmeas mg1 c1`
2. delete measurement group `mg`: `udefmeas mg1`
3. create a measurement group `mg1` with a channel `c2`: `defmeas mg1 c2` (this channel `c2` should belong to a different controller than `c1`)

now we cannot operate the measurement group because the configuration still sees the old c1:
```
Door_bl04_1 [10]: ct
Thu Mar 18 12:07:51 2021

Elements ended acquisition with:
d1d_1:
       State: On (12:07:42.859062)
      Status: c2 is On
              Stopped (12:07:51.041025)
An error occurred while running ct:
PyDs_PythonError: Exception: The synchronization description group has not been initialized

Hint: in Spock execute `www`to get more details

Door_bl04_1 [11]: get_meas_conf all
ActiveMntGrp = mg1
An error occurred while running get_meas_conf:
DB_DeviceNotDefined: device controller/dummyctctrl/dummy2_ctrl not defined in the database !
Hint: in Spock execute `www`to get more details
```

**Comment by tiagocoutinho** [comment]
suggestion for fix:
When removing a measurement group, the pool should also clean the tango properties of that group and also the attribute properties since apparently tango does do it.

**Comment by reszelaz** [comment]
Hi @tiagocoutinho,
Thanks for the report! This is an old issue. It was reported in https://github.com/sardana-org/sardana/issues/145.
At some point, we were trying to fix it with @amilan but at that time we were blocked by a bug in Tango 8. I even have a local branch from that time with the fix and I will try to update it with the develop branch and try it again. I think it should work now, or be very close to the working state because we don't need to care about Tango 8 anymore.
Meanwhile I propose to close this issue as a duplicate.
