### ISSUE TITLE
Hooks by default in scans (SF#354)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#200]
Hi,
       I copy here an e-mail that I sent some time ago, it has
 become now a request from our users.

   our beamline scientists want that all the scans run by default
 with hooks functions, not like it is now that it is necessary to define
 a new macro running an existing scan macro after adding hooks to it.
 They want to keep the original names for the current scan macros and
 simply define a function that will be run always like a hook.
 I think that the current implementation for the hooks works quite
 well, and offers flexibility for example for the arguments that have
 to be passed. A fixed function could have some problem there.
 So in my opinion one should keep what is implemented and try to
 add the requested feature that could be activated by an additional
 variable (set for example in the spock environment).
 What do you think about something like this?. 

                            Regards,
                                       Teresa

Reported by: teresanunez ( http://sf.net/u/tere29 )

Original Ticket: [sardana/tickets/354](https://sourceforge.net/p/sardana/tickets/354)

**Comment by teresanunez** [comment]
Hi Zibi, I have read all that again and I think we have a different idea of what a general hook is.
 For us a general hook will be never called or set by the programmer in any other macro, for that
 we have already the standard hooks. This was exactly the reason why we have implemented the
 general hooks, they are something that applies always and nothing have to know or program anything
extra in any other macro.
About breaking the scan if there is an error in the general hook, we have discussed this point with
 our users, and they want the scan to continue and get only a warning about the execution of the
 general hook. Perhaps one can implement the possibility of choosing what to do.
We would also prefer not to give too much flexibility in choosing between macros or functions for
 the general hooks. We have tested both cases and the users are more happy with macros (except
 for the case of the on_stop function, since no macro can be executed after a control-C, but I am 
 not sure if this has been changed recently). 
So I do not really know how to proceed with that for getting it integrated.

**Comment by reszelaz** [comment]
I have some comments regarding the GeneralHooks syntax proposed in https://github.com/sardana-org/sardana/issues/200#issuecomment-262975158.
The proposed general hook map uses the hook place name as the key and the list with macro(s) to be executed at that hook place as values. This syntax is somehow opposite to what we currently have for setting hooks programmatically.

See documentation: https://github.com/sardana-org/sardana/blob/01b154244c97e09b316be39fbf2e7a15d149e4f3/src/sardana/macroserver/macro.py#L210
And example:
https://github.com/sardana-org/sardana/blob/01b154244c97e09b316be39fbf2e7a15d149e4f3/src/sardana/macroserver/macros/examples/hooks.py#L161
If we assume that this map is an internal data structure not intended to be directly set by the user it is fine. But then, when providing the user macros for dealing with the general hooks, IMHO, we should keep the syntax already used in the programmatic way. In other words, if the user would like to set all general hooks in a one shot, the syntax should use the macro as the key and the list of hook places as the values. 

Apart from the fact that this is more coherent with what we have now, if the same macro has to be called at more than one hook place it avoids duplication of configuration. By the way, setting all general hooks in one shot is rather a complicated operation for the user, so I would also provide macros for adding partial configuration.

**Comment by reszelaz** [comment]
From the implementation point of view it would be much easier to use the internal data structure of GeneralHooks environment variable in the same form as it is already used in the programmatic way of setting hooks.

**Comment by cpascual** [comment]
I agree 100% in the value of keeping the environment syntax closer to the programmatic one.

But, on the other hand, note that the keys of a dictionary must be hashable, while the values can be anything. In the syntax [I proposed](https://github.com/sardana-org/sardana/issues/200#issuecomment-262975158) this is granted since the hook-place names are hashable. And therefore one can:

- assign any callable in a hook (not only macros identified by name, but also functions)
- pass arbitrary args and kwargs to the callable 

I suppose that the first thing could also be accomplished in the *"closer-to-programmatic"* syntax by allowing  the user to provide the *name* of a function (including its module), but support arbitrary args and kwargs would be a lot more difficult.

With this I am not saying that we should use my proposed syntax. I am only noting this limitation for all to be aware when evaluating the best solution.

**Comment by reszelaz** [comment]
The current programmatic API is based on the Hookable class which comprises a property called hooks. This property is a list of lists/tuples. Each of the internal lists has two elements, the first one is the hook itself and the second one is the list of hints, now used as hook places. It works with callables (arguments are currently not supported) and macros via the https://github.com/sardana-org/sardana/blob/01b154244c97e09b316be39fbf2e7a15d149e4f3/src/sardana/macroserver/macro.py#L255 helper class (parameters are supported). So, if we would like to maintain this format, we won’t be affected by the “unhashable key” problem mentioned in https://github.com/sardana-org/sardana/issues/200#issuecomment-343838853.

**Comment by cpascual** [comment]
Seems like a good option to me
