### ISSUE TITLE
spock returns prompt after ctrl+c even if the macro is still running (SF#47)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#34]
This issue was reported by Francois Fauth.

If in the macro code, a long time.sleep() gets called and the macro is aborted during this sleep, spock returns the prompt even if the macro is still running.

Furthermore it informs the user that stopping was correctly done:

~~~
^C
Ctrl-C received: Stopping... Done!
~~~
However if you ask the spock about the door state, it reports that macro is still running:

~~~
Door_XXX [58]: _DOOR.state()
Result [58]: PyTango._PyTango.DevState.RUNNING
~~~

This way user could get confused, and execute another macro. The subsequent macro gets queued, and does not start until the previous macro execution reaches a checkPoint() call.

Please see attached python module with two macro examples: `abort_fail` and `abort_pass`

Reported by: reszelaz ( http://sf.net/u/zreszela )

Original Ticket: [sardana/tickets/47](https://sourceforge.net/p/sardana/tickets/47)

**Comment by reszelaz** [comment]
This issue is addressed in PR #596.

I have also received some internal comments at Alba that we could print some intermediate messages while the macro is being stopped, below two proposals.
1. Give a detailed messages what is goind on:
Acquisition action stopped
Motion action stopped
submacro <____> stopped
2. Give periodic messages that something is going on:
.
after 300ms:
..
after 300ms:
...
Anyway, I would treat them as separate feature requests.
