### ISSUE TITLE
not timer in pool elements

### ISSUE THREAD

**Issue by jkotan** [sardana-org/sardana#444]
Hi,

After merging SEP6 I started to get the following error:

    SardanaTP.W004 ERROR    2017-04-05 08:07:19,303 SardanaTP.SardanaTP.W004: Uncaught exception running job 'run' called from thread SardanaTP.W002:
      File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
	self.__bootstrap_inner()
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
	self.run()
      File "/usr/lib/python2.7/dist-packages/taurus/core/util/threadpool.py", line 134, in run
	cmd(*args, **kw)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/util/funcgenerator.py", line 167, in run
	self.fire_active()
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/util/funcgenerator.py", line 223, in fire_active
	self.fire_event(EventType("active"), self._id)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/sardanaevent.py", line 110, in fire_event
	self._fire_event(event_type, event_value, listeners=listeners)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/sardanaevent.py", line 130, in _fire_event
	real_listener.event_received(self, event_type, event_value)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/pool/poolacquisition.py", line 244, in event_received
	get_thread_pool().add(self._sw_acq.run, *args, **kwargs)
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/taurus/core/util/threadpool.py", line 134, in run
	cmd(*args, **kw)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/pool/poolaction.py", line 339, in run
	self.start_action(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/taurus/core/util/log.py", line 156, in wrapper
	ret = f(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/pool/poolacquisition.py", line 737, in start_action
	PoolAcquisitionBase.start_action(self, *args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/taurus/core/util/log.py", line 156, in wrapper
	ret = f(*args, **kwargs)
      File "/home/jkotan/testsar/lib/python2.7/site-packages/sardana-2.2.4_alpha-py2.7.egg/sardana/pool/poolacquisition.py", line 602, in start_action
	elements.remove(timer_monitor)
    ValueError: list.remove(x): x not in list

It looks like `timer` is not in `elements` list.

Bests,
Jan

**Comment by reszelaz** [comment]
Could you please provide the exact steps to reproduce this problem?

**Comment by teresanunez** [comment]
I wanted to ask the same ... because I do not have that problem also here at DESY ...

**Comment by jkotan** [comment]
Hi, 
I've just started Pool and MacroServer  in terminals, open spock, run from spock expconf, apply measurement group (only with fio recorder) and run the scan in spock:

     ascan exp_mot04 0 1 2 0.1

From the spock It looks like that everything is OK. The error appears only in my Pool terminal.

My configuration of the measurement group is (I assume It was automatically converted from the old version):

	{"controllers":{"haso228k:10000/controller/sis3820ctrl/sis3820_exp":{"synchronizer":"software","channels":{"haso228k:10000/expchan/sis3820_exp/2":{"ndim":0,"plot_type":1,"full_name":"haso228k:10000/expchan/sis3820_exp/2","data_type":"float64","nexus_path":"","shape":[],"conditioning":"","plot_axes":["<mov>"],"_unit_id":"0","normalization":0,"index":2,"name":"exp_c02","source":"haso228k:10000/expchan/sis3820_exp/2/Value","enabled":true,"label":"exp_c02","instrument":null,"_controller_name":"haso228k:10000/controller/sis3820ctrl/sis3820_exp","data_units":"","output":true},"haso228k:10000/expchan/sis3820_exp/1":{"ndim":0,"plot_type":1,"full_name":"haso228k:10000/expchan/sis3820_exp/1","data_type":"float64","nexus_path":"","shape":[],"conditioning":"","plot_axes":["<mov>"],"_unit_id":"0","normalization":0,"index":1,"name":"exp_c01","source":"haso228k:10000/expchan/sis3820_exp/1/Value","enabled":true,"label":"exp_c01","instrument":null,"_controller_name":"haso228k:10000/controller/sis3820ctrl/sis3820_exp","data_units":"","output":true}},"synchronization":0,"monitor":"haso228k:10000/expchan/dgg2_exp_01/1","timer":"haso228k:10000/expchan/dgg2_exp_01/1"},"haso228k:10000/controller/dgg2ctrl/dgg2_exp_01":{"synchronizer":"software","channels":{"haso228k:10000/expchan/dgg2_exp_01/1":{"ndim":0,"plot_type":0,"full_name":"haso228k:10000/expchan/dgg2_exp_01/1","data_type":"float64","nexus_path":"","shape":[],"conditioning":"","plot_axes":[],"_unit_id":"0","normalization":0,"index":3,"name":"exp_t01","source":"haso228k:10000/expchan/dgg2_exp_01/1/Value","enabled":true,"label":"exp_t01","instrument":null,"_controller_name":"haso228k:10000/controller/dgg2ctrl/dgg2_exp_01","data_units":"","output":true}},"synchronization":0,"monitor":"haso228k:10000/expchan/dgg2_exp_01/1","timer":"haso228k:10000/expchan/dgg2_exp_01/1"},"haso228k:10000/controller/hasyadcctrl/tip830_exp":{"channels":{"haso228k:10000/expchan/tip830_exp/5":{"ndim":0,"plot_type":1,"full_name":"haso228k:10000/expchan/tip830_exp/5","data_type":"float64","nexus_path":"","shape":[],"conditioning":"","plot_axes":["<mov>"],"_unit_id":"0","normalization":0,"index":0,"name":"exp_adc05","source":"haso228k:10000/expchan/tip830_exp/5/Value","enabled":true,"label":"exp_adc05","instrument":null,"_controller_name":"haso228k:10000/controller/hasyadcctrl/tip830_exp","data_units":"","output":true}}},"__tango__":{"channels":{"haso228k.desy.de:10000/motor/dummy_mot_ctrl/1/acceleration":{"ndim":null,"plot_type":1,"full_name":"tango://haso228k.desy.de:10000/motor/dummy_mot_ctrl/1/acceleration","data_type":"float64","nexus_path":"","shape":[],"conditioning":"","plot_axes":["<mov>"],"_unit_id":"0","normalization":0,"index":4,"name":"acceleration_1","source":"tango://haso228k.desy.de:10000/motor/dummy_mot_ctrl/1/acceleration","enabled":true,"label":"motor/dummy_mot_ctrl/1/acceleration","instrument":null,"_controller_name":"__tango__","data_units":"","output":true}}}},"description":"Measurement Group","monitor":"haso228k:10000/expchan/dgg2_exp_01/1","timer":"haso228k:10000/expchan/dgg2_exp_01/1","label":"mg_test01"}




Cheers,
Jan

**Comment by teresanunez** [comment]
Hi Jan,
                    I have just done the same you describe, also using the fio recorder and I do not get any
 error.
                              Regards,
                                               Teresa

**Comment by teresanunez** [comment]
Jan, what are you using?, the pure Sardana develop version or have you make a merge with some
 changes we have in DESY?. I am using the pure one.

**Comment by jkotan** [comment]
I use pure sardana without desy code.

**Comment by jkotan** [comment]
Hi Teresa and Zibi,

I removed (using expconf) from mg everything except a timer and a counter but I still get this error.
Is something wrong with my mg configuration:

    {"controllers":{"haso228k:10000/controller/sis3820ctrl/sis3820_exp":{"synchronizer":"software","channels":{"haso228k:10000/expchan/sis3820_exp/1":{"ndim":0,"plot_type":1,"full_name":"haso228k:10000/expchan/sis3820_exp/1","data_type":"float64","nexus_path":"","shape":[],"conditioning":"","plot_axes":["<mov>"],"_unit_id":"0","normalization":0,"index":0,"name":"exp_c01","source":"haso228k:10000/expchan/sis3820_exp/1/Value","enabled":true,"label":"exp_c01","instrument":null,"_controller_name":"haso228k:10000/controller/sis3820ctrl/sis3820_exp","data_units":"","output":true}},"synchronization":0,"monitor":"haso228k:10000/expchan/dgg2_exp_01/1","timer":"haso228k:10000/expchan/dgg2_exp_01/1"},"haso228k:10000/controller/dgg2ctrl/dgg2_exp_01":{"synchronizer":"software","channels":{"haso228k:10000/expchan/dgg2_exp_01/1":{"ndim":0,"plot_type":0,"full_name":"haso228k:10000/expchan/dgg2_exp_01/1","data_type":"float64","nexus_path":"","shape":[],"conditioning":"","plot_axes":[],"_unit_id":"0","normalization":0,"index":1,"name":"exp_t01","source":"haso228k:10000/expchan/dgg2_exp_01/1/Value","enabled":true,"label":"exp_t01","instrument":null,"_controller_name":"haso228k:10000/controller/dgg2ctrl/dgg2_exp_01","data_units":"","output":true}},"synchronization":0,"monitor":"haso228k:10000/expchan/dgg2_exp_01/1","timer":"haso228k:10000/expchan/dgg2_exp_01/1"}},"description":"Measurement Group","monitor":"haso228k:10000/expchan/dgg2_exp_01/1","timer":"haso228k:10000/expchan/dgg2_exp_01/1","label":"mg_test01"}

Cheers,
Jan

**Comment by teresanunez** [comment]
Try starting again sardana from scratch (perhaps you have modified something in the configuration
 with some other tools).

**Comment by reszelaz** [comment]
At the moment I cannot check it. I will reply before tomorrow. Thanks for the report!

**Comment by jkotan** [comment]
Hi Teresa,

I've just created from the scratch new measurement group. It works but configuration is strange, i.e. 
valued for "timer" and "monitor" is assigned to counter device name.

Probably that cause the problem. Is it really the case we should use counter as a timer?

Cheers,
Jan

**Comment by teresanunez** [comment]
Hi Jan,
              at the end of the configuration you have the values:

"description":"General purpose measurement group","monitor":"haso111n:10000/expchan/dgg2_exp_01/1","timer":"haso111n:10000/expchan/dgg2_exp_01/1","label":"mg_test"

Both monitor and timer are the timer I have.

**Comment by jkotan** [comment]
Hi Teresa,

at the end of configuration  you get "timer" and "monitor" depending in which order you add experimental channels (In expconf you cannot change it later which should not be the case). 

The key point to the error I found is "timer" and "monitor" of controllers, i.e. I had "timers/monitors" set to "haso111n:10000/expchan/dgg2_exp_01/1". If I set "timer" for counter to my sis counter the error has disappeared.

Is there any documentation where one can read which 'timer' is what? Configuration of MG is a Tango attribute so it bellongs to public interface and it should be somewhere documented. (Before setting all timer to one value was working OK).

PS: I've just also noticed that `_unit_id` has been also removed.

Cheers,
Jan

**Comment by reszelaz** [comment]
The exception comes from the part of the acquisition start algorithm, where the controller’s channels are organized in such a way that the timer/monitor is started as the last one. This indeed was changed with the SEP6 integration but as a fix for #375.

The assumption which I did when implementing it was that the controller’s timer/monitor will always belong to the said controller. I simply followed the rule that implements the `expconf`, where it is not possible to select an element not belonging to the controller as the controller’s timer. But maybe this assumption is wrong.

Just to clarify, the example that provokes this bug is using a channel from one controller as timer/monitor in another controller.

First,  we should dig in our memory why the `expconf` was implemented in such a way? Was it a part of the specification, or was it just left for the future developments to allow selection of the controller’s timers coming from an arbitrary controller. Maybe @cpascual remembers that?

Second, could you please share some details about the hardware configuration used in this measurement group? I have google a little bit about DGG2 and SIS3820 but it is better that you explain how does they work. I see that you use DGG2 as a timer for SIS3820 channels. I have some questions in order to better understand this setup:

- Can the DGG2 channels work as counters?
- I assume that both cards are wired together with an external cable to propagate some hardware gate signal, isn’t it?
- Can the DGG2 timer channel generate multiple gate signals with a single start i.e. work in a time driven continuous acquisition? Or it must be started by software each time it generates a gate?

At Alba, we just have one similar case, where multiple NI6602 cards are connected via the RTSI bus and a single timer is used for channels coming from different cards. In this case we could define all the channels as members of the same controller, so the `expconf` could be used to select the timer/monitor easily.

Before implementing the solution to your problem we should clarify if we admit to select controller’s timer/monitor from any controller. Any opinions?

Now my answers to the other topics:

- I confirm that expconf does not allow to change the measurement group’s master timer nor the master monitor. This bug was present in the develop before integrating the SEP6. Can you fill the bug report, please.
- I also admit that the documentation is very poor, especially about the acquisition part of Sardana. We will do our best in order to improve it, actually the SEP6 brought some new chapters… Apart of that any contributions to the documentation will be very welcome!
- Regarding the `_unit_id` it disappeared with #218. Do you still need it?

**Comment by jkotan** [comment]
Hi,

From our perspective is mostly backward compatibility problem, i.e. we have often created measurement groups with timer from different controllers. However, probably we can change it. We recreate our measurement groups from scratch by our tools so problems  can have only our users who instead of our tools will use expconf to apply the measurement group. Actually, this error is quite hidden (info do not appears in the spock) so use may not even notice that something is wrong.

As I understand the information about timer/monitors is used mostly by controller parts and it deeply depends on their implementation. I thought  that it is some arbitrary info to controller and depending on the type of the controller it is used properly. Now for me `timer` device is somehow related to `synchronizer`.

I think our expert in implementation of dgg2 and sis3802 (tango servers, controllers and their working logic) is Teresa. Teresa, could you please provide us more details about our timer/counter devices, its implementation, logic and what  we need (controller timers or master timers) for our controllers?

Since we recreate the measurement group we need to know detail structure of the new MG configuration. That why I asked about `_unit_id` by we don't need it.

Bests,
Jan

**Comment by reszelaz** [comment]
Up to now timer and monitors were used in the following way:

- Each of the timerable controllers (CT, 1D, 2D) implements timer and monitor controller parameters. These parameters are set with the axis number of the timer/monitor channel selected in the measurement group configuration and loaded on the acquisition startup.
- LoadOne method is called only on the selected timer/monitor axis.
- Timer and monitors start acquiring as the last ones.
- There is one master timer and monitor per measurement group which is started as the last one of all timers or monitors

I totally agree that the timer or monitor and the synchronizer somehow competes for the same role. On the Sardana Workshop at DESY I have even presented a proposal on eliminating timers and monitors from the measurement group configuration on favor of the synchronizers only. But finally this plan was not completed due to:

- lack of time - we wanted to close the SEP6 as soon as possible
- still some doubts if we will not lose flexibility in configuration of the really complex applications
- complex rules to decide on which axis we call LoadOne, how do we set timer or monitor controller logic…
- expconf will require to implement a complex logic in order to offer the correct options to select synchronizers
- possible backwards compatibility difficulties

But still, it is very important to know different applications that you use at your sites - at Alba we don’t have a big variety of them. So please share yours and we can discuss how they fit into what we have in Sardanda now and will help in designing the improvements.

**Comment by jkotan** [comment]
Hi Zibi,

Many thanks for your detailed explanation. 

I was looking at the code of our controllers and tango servers and I haven't found and usage of controller timers/monitors. 
So since we recreate our MGs it looks like that from our side there is no need to change the implementation. Looking at the output of expconf I've learned that new allowed  values for controller timer/monitors are:

    a)  for CT, 1D, 2D channels: timer/monitor  ~ one of controller devices 
    b)  for OD Tango channels: timer/monitor not defined

(Before controller timer/monitor ware not so restricted.)
But since we recreate our MGs and we do not use timer/monitors it looks like that from our side there is no need to change the implementation.

Bests,
Jan

**Comment by teresanunez** [comment]
No need to do anything.
