### ISSUE TITLE
make all sardana PEP8 compliant (SF#81)

### ISSUE THREAD

**Issue by sf-migrator-bot** [sardana-org/sardana#54]
It can be done with autopep8, but tweaking it so that it does n not ugly things.

For example, I tried autopep8 with its default settings and observed that:

```~
foo = bar - 1 # long comment that goes over col=79....
                      
```~

gets transformed into:

```~
foo = bar -  \ 
          1 # long comment that goes over col=79....
```~

and I would prefer something like:

```~
foo = bar -  1 # here I write a very long 
               # comment that goes 
               # over col=79....
```~




Reported by: cpascual ( http://sf.net/u/cpascual )

Original Ticket: [sardana/tickets/81](https://sourceforge.net/p/sardana/tickets/81)

**Comment by reszelaz** [comment]
I start working on it. This will have a big impact on developments started prior to these changes - it will make it difficult to merge them later on. I think that there are no big developments apart of SEP8. I have briefly talked with @cmft and he gave me green light to make the changes - it is not planned to integrate the SEP8 soon...

The work will basically follow what was [done](https://github.com/taurus-org/taurus/issues/298) for Taurus. I also plan to add a check to travis that will evaluate (PEP8) the diff corresponding to a new pull request. This way if a pull request is not PEP8 compliant it will be marked as red by travis. Of course we will agree on the critical errors, but I would use the criteria that will be applied in this issue.

**Comment by cpascual** [comment]
> I also plan to add a check to travis that will evaluate (PEP8) the diff corresponding to a new pull request.

Great news! I wanted to have that in Taurus as well...

**Comment by reszelaz** [comment]
Basically I have followed the steps done for Taurus (thanks @cpascual for leaving it well documented). I have also avoided applying corrections for E501 (line too long (82 > 79 characters)) cause in many cases it leaves the code not really readable. Unfortunately we will need to apply these corrections manually. The only difference with respect to Taurus is that I have applied:

- E712 (^)	comparison to True should be ‘if cond is True:’ or ‘if cond:’
- E721 (^)	do not compare types, use ‘isinstance()’

since in case of Sardana these do not break any tests and I consider that the testsuite is quite complete having in mind that it comprises high level functional tests e.g. executing scans and other macros on a sar_demo environment..

The only thing which warns me is that the default autopep8 execution changed the license header. But I assume it is normal since we have accepted that for Taurus.

With #446 we will reduce the number of flake8 errors from 21106 to 3828 leaving the following ones:
~~~
3     E113 unexpected indentation
34    E114 indentation is not a multiple of four (comment)
3     E211 whitespace before '('
485   E265 block comment should start with '# '
24    E266 too many leading '#' for block comment
92    E305 expected 2 blank lines after class or function definition, found 1
28    E402 module level import not at top of file
2297  E501 line too long (80 > 79 characters)
21    E713 test for membership should be 'not in'
51    E714 test for object identity should be 'is not'
3     E731 do not assign a lambda expression, use a def
96    E999 SyntaxError: invalid syntax
208   F401 'rst2pdf.pdfbuilder' imported but unused
54    F403 'from types import *' used; unable to detect undefined names
226   F405 'QWizard' may be undefined, or defined from star imports: types
5     F811 redefinition of unused 'sys' from line 2
59    F821 undefined name 'tau'
17    F822 undefined name 'TriggerGate' in __all__
33    F841 local variable 'tblexer' is assigned to but never used
57    W601 .has_key() is deprecated, use 'in'
32    W602 deprecated form of raising exception
3828
~~~

Now I will work on the travis-ci check for PEP8 compliance.

**Comment by reszelaz** [comment]
After investigating a little bit I found the following two projects which have a nice flake8 check (diff only) implemented in travis: [joblib](https://github.com/joblib/joblib) and [scikit-learn](https://github.com/scikit-learn/scikit-learn).

I think that their script covers our needs. Apart of its main use case - run it in travis-ci, the same script can be used to check flake8 errors on the local branch in comparison with the canonical develop branch. The script is also ready to be eventually run in travis-ci of a fork project. It has one known minor drawback (in comparison to the benefits), that it is not able to discover E305 (expected 2 blank lines after end of function or class) when introduced on the diff boundary, but I think that we can live with that for the moment.

I have submitted these two PR: #450 and #449 . Both implements the flake8 check. The first one adds flake8 check. The second one does the same and additionally, for the demo purposes, violates some flake8 rules. The idea is to discard the second PR.

After integrating #446 and #450 I consider this issue as resolved. @sardana-org/integrators please can you take a look?
