### ISSUE TITLE
Failed relmaclib and addmaclib

### ISSUE THREAD

**Issue by daneos** [sardana-org/sardana#564]
One of the ideas from Sardana Workshop at Solaris.

It is painfull for the users to have to call the `addmaclib` macro when previously the `relmaclib` failed e.g. due to the syntax error and the library was eliminated from system.
Then, if we want to try to reload the module adain, we have to use the `addmaclib` macro.
It would be good if `relmaclib` could be used even if the macro library is not currently loaded.

**Comment by mrosanes** [comment]
In principle, if the macro is already correctly loaded in the system, and then ```relmaclib``` is used, if the relmaclib fails, the macro library is not eliminated from the system, instead, the old macro library is kept, and a message indicating this fact appears in spock: ```The old macro library is still available```.

When the error is solved and relmaclib is called again, the macro is reloaded. 
Thus, the fact described in the ticket: "...when previously the relmaclib failed e.g. due to the syntax error and the library was eliminated from system.", it does not happen as of today in sardana.

**Comment by daneos** [comment]
We created our list based on Sardana 2.2.2, but indeed, new Sardana has this problem fixed, so I'm closing this issue.
Thanks!
