### ISSUE TITLE
nested scans with sequencer

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#744]
Hej all,

I would like to use the sequencer for doing a set of nested scans similar to a mesh scan but having a single scan for the inner loop in the SPEC file.
Following the sequencer example in the documentation I simply nested two ascans for example having an outer loop for motorA and an inner loop for motorB, which is the one I would like to have my individual scans in the SPEC file.
Now the problem is that sardana also acquires data for the outer loop and also saves them into the SPEC file. This to some extent corrupts the SPEC file because there is an extra line of data atfer each scan of the inner loop. So i.e. PyMCA puts this last line of data into one of the inner loop scans.

My question is now, if there is a macro that is just scanning a motor without acquiring data and which is also compatible with the sequencer?

In good old SPEC I would have writting a simple macro with some for-loops instead, but I pretty much appriciate the Sequencer of Sardana. If there is no such scanning macro available I might try to write my own.

Best

Daniel

**Comment by teresanunez** [comment]
Hi Daniel,
                   if you set in the sequencer something like it is in 
the attached image you
  get in the file only the scans of the inner motor, the outer motor 
does not appear.
  Perhaps this helps.

                             Regards,
                                              Teresa

**Comment by teresanunez** [comment]
Hi again, 
                I am not sure if the image was attached, what I mean is to add the macro:

senv ScanFile mytestname.spec

before the inner scan and the macro:

usenv ScanFile

after the inner scan.

                          Regards,
                                             Teresa
![send](https://user-images.githubusercontent.com/5548680/39815724-4ad8aa6a-5399-11e8-8173-22fcf3b39013.jpeg)

**Comment by reszelaz** [comment]
Very good idea @teresanunez!  I would also do it this way. I think it should enough to usenv the ScanFile just once - before the outer scan. This is because the scan creates the recorders at the beginning of the execution. Then the ScanFile environment variable is not evaluated in between the scan steps.

The only disadvantage is that the acquisition will take place anyway. Maybe you could create a dummy measurement group and play with the ActiveMntGrp environment variable in a similar way...
Actually, I think it should not be too difficult to make the scan to not acquire if the ActiveMntGrp is not defined and just scan the motor as you said.

Hope that this solution is good enough for your needs.

**Comment by dschick** [comment]
thanks a lot.
seems like a workaround that should do it.
Is there also a macro to just repeat a scan several times like in a loop?

Best

Daniel

**Comment by reszelaz** [comment]
Maybe at the end of the day I will have some time to reproduce it. Meanwhile, just to ensure, have you set the hook place (right mouse click on the macro in the tree) for the senv macro to be run before the internal scan (it has to be at lest the same hook place as the one of the internal scan)?

**Comment by reszelaz** [comment]
@dschick you hit a bug that was recently introduced by #655. I have submitted #747 in order to fix it.

**Comment by dschick** [comment]
hej,

havn't had time to test bug fix yet, but I was just thinking if it would be even more convinient for the user to disable data acquisition by simply setting the integration time to 0 or even < 0.
In this case one could use any kind of scan macro to just move the motors and not saving data to the file. This should also work for the sequencer then.

What do you think?

**Comment by reszelaz** [comment]
I agree that it would be interesting to disable data acquisition in a scan.

With respect to your proposals, the negative integration times are currently used to configure the measurement group in the monitor mode (count to monitor value). And the 0 integration time is used to just read the experimental channel values without loading the controllers with the integration times and starting the acquisition. The purpose of this last option is not very clear to me when one uses measurement groups with Sardana experimental channels - see [SEP17](https://github.com/sardana-org/sardana/pull/478) discussion on how the experimental channel value attribute should behave. However it has sense if one uses external attributes e.g. Tango attributes in the measurement group. So, in summary, I think that both options that you propose are already reserved for other functions. 

Personally, I like more the idea of disabling data acquisition by undefining `ActiveMntGrp` environment variable. This is because there are other information that is stored in the scan entry that is not directly related to data acqusition. For example if the pre-scan snapshot is configured (`PreScanSnapshot` environment variable) the scan performs the snapshot and stores its data in the file. So if you would like to avoid writing to the file, I think the best is to undefine the `ScanFile` environment variable,

**Comment by dschick** [comment]
due to #747 the nesting works now as expected when I also take care of the hooks.
I tested to set the hook of `senv `and the inner `ascan `to be `post-move` and for the `usenv `it is `pre-acquisition`.

Although this way of nesting scans seems to be quite powerful I have the feeling that it is rather user unfriendly. Especially when nesting several parameters and scans.

If the integration time is already reserved for other purposes I would suggest introducing new macros, like the `repeat `one to enable scanning of motors without acquisition. I would try to implement such macros starting from the default ascan macro and ripping out the data acquisition part.
