### ISSUE TITLE
axisExtraPar not available in axisPar

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#755]
I implemented a simple motor controller (Newport XPS) which requires a name for each axis for communication. Therefor I added an axisExtraPar to the controller class and after %defelem in spock I set the axisExtraPar via Jive. This works well for accessing this axis name extra parameter from within the default methods like StartOne, ReadOne, etc.

I then tried to implement the Get/SetAxisPar methods for accelleration and velocity which again needs the axis name extra parameter for communication. But somehow in these methods the extraPar is not availabe. Not during initialization nor in a later call. The extraPar is only availabe when I set it in the addDevice method.

Is this behaviour intended?

Best

Daniel

**Comment by reszelaz** [comment]
@dschick sorry for so late reply. Hope this information will still be helpful for you..

> Therefor I added an axisExtraPar to the controller class and after %defelem in spock I set the axisExtraPar via Jive.

Just to complete this, the sardana element attributes e.g. motor attributes like the acceleration, or any other axis attribute, can be set directly from spock: `mot01.acceleration = 0.3`

> I then tried to implement the Get/SetAxisPar methods for accelleration and velocity which again needs the axis name extra parameter for communication. But somehow in these methods the extraPar is not availabe. Not during initialization nor in a later call.

By initialization you mean on the Pool/Sardana server startup? In this case, the `SetAxisPar` gives you an exception because the `SetAxisExtraPar` was not yet called and the communication name is unknown? 

What do you mean by later call? After the server startup, for example in spock, when you set the acceleration or velocity, the communication name is still unknown?

While the first thing does not surprises me, the second yes.

I explain the first behavior. These attributes are Tango memorized attributes. Their values are recovered from the database and set on the server startup (more preciselly in the device initialization process, after calling `init_device`). As far as I know the order in which these memorized attribute values are applied is uknown or better said we should not rely on it. Maybe some Tango experts could comment on this?

Could you please explain with more details the second behavior?

> The extraPar is only availabe when I set it in the addDevice method.

Yes, `addDevice` should work cause it is still called within the `init_device`. But you must hardcode the communication name there, don't you? From my experience I usually used the controller properties for these communication names, or as it is done in case of the IcePAP controller, the axis number is at the same time the communication address.

> Is this behaviour intended?

As I said, we should explore the Tango technical possibilities about determining the order of memorized attributes application. And then discuss if we want to allow the controller developers to define this order.

**Comment by reszelaz** [comment]
Hi @dschick, I'm just reviewing the old issues marked as _question_. I'll proceed to close this one, unless you have some more details which could help us in defining a bug report or enhancement proposal? Thanks a lot!
