### ISSUE TITLE
newfile macro

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#776]
I am actually missing a `newfile ` macro which set a new data file, resets the scanID to 1 and also writes a proper scanFileHeader for SPEC files.

As some analysis software requires a proper SPEC file header containing the motor and counter names such as here:

```
#F 2017-08-Schick-02
#E 1502445176
#D Fri Aug 11 11:52:56 2017
#C fourc  User = specadm

#O0 TwoTheta  Theta  Chi  Phi  mono  threl  xs  ys
#O1 zs  Energy  DetHeight  CCDH  MagnetHeight  FYHeight  MagnetRot  Current
#O2 TwoThetaR  Volt  ExitSlit  Lake  
#o0 tth th chi phi mono threl xs ys
#o1 zs en deth ccdh mh fyh mr cur
#o2 tthr volt exs lake 

#J0 Seconds  Monitor  Detector  Drain  Energy  Ringcurr  Tsample  Tcryo
#J1 Theta  TwoTheta  Gap  Shift  GapD  ShiftD  Bandwidth  PSDPos
#j0 sec mon det drain e ri tsample tcryo
#j1 theta twoth gap shift gapD shiftD bw psdpos
```

I guess it should not be to hard to do the first to things, namely changing the ScanFile and the ScanID from within a macro accessing the environment variables.
Where would one write a scan file header? In the init method of the according recorder class?

Best

Daniel

**Comment by reszelaz** [comment]
Thanks for this suggestion! Actually it sounds familiar to me.. If I remember correctly we all agreed on the Sardana Workshop in 2015 that it would be nice to have the`newfile` macro in Sardana. The only thing is that we did not have time to implement it yet..

At that time the proposal was to use the repeat parameter in the macro to be able to set multiple files (set `ScanFile` environment variable in a more user friendly way). I assume that at that time we were not thinking about resetting the `ScanID`, but I think it make sense. Or at least we could give another macro parameter (bool) if one wants to reset it or not, with a default value.

Regarding the scan file header, I think we should go for it (see this recommendation: https://github.com/sardana-org/sardana/issues/735#issuecomment-382312675).

We just need to agree on some things:
* Is `#F` an absolute path: \<ScanDir\> + "/" \<Spec file name extracted from ScanFile\> ?
* According to [Spec's Standard Data File Format](https://certif.com/spec_manual/user_1_4_1.html) the `#E` keeps the epoch when the file was created. And then there is a column in each scan with the relative seconds from that epoch. We have already the `dt` column witht the relative time from the scan's start. We need to decide the strategy here as well... 
* We need to agree on how to implement the comments (`#C`), only if they are necessary. We already talked a little bit about it in #771. If I understands correctly, in SPEC one sets them in between the scans executions. In this case this would need to be stored somewhere, hence I proposed the environment which would provide the persistence. The comment could be set by the `comment` macro...
* We already use `#O` (together with `#P`) for the snapshot. I imagine that the `#O` in the scan file header is for the same purpose. The only difference is that it is static for the whole file? And in case of the Sardana's snapshot it could change in between the scans, hence it is placed within the scan entry. Would it be fine if we just not include it in scan file header and keep it as we us it now?
* What should we put in the `#J`? Or maybe we could just skip it?
* The same applies to the mnemonic fields (`#o` and `#j`) could we just skip them?

I think that the implementation could be done incrementally. I mean we could already add the `newfile` macro. The recorder's stuff could be added afterwards.. @dschick it would be great if you could help with this.

**Comment by reszelaz** [comment]
> so I guess there is no need to check the ScanID for validity.

I agree.

> I think it is just the actual file name and not including the path at all

Accoring to the example from [Spec's Standard Data File Format](https://certif.com/spec_manual/user_1_4_1.html) I would say it is a full path. So, in Sardana I would also use the full path: \<ScanDir\> + "/" \<Spec file name extracted from ScanFile\>.

> I guess the #E field will not hurt and dt makes sense as well especially as there should be no epoch saved in the #D field as pointed out in #766 - otherwise e.g. xrayutilities will fail to parse the file.

Ok, it seems clear that `#E` should contain the epoch in the file header. Then, the `dt` column, to be useful for representing the scan records agains the abosulte time, would require another `#E` with the epoch in the scan header (since now the `#D` contains the information in the date time format). Do you think it may harm?

> At the end, it would be sufficient to have one comment macro which one can use from within the command line to put some comments into the file between the scans (this would act as some additional lab-book resource) and one should be able to hook this macro eg. to the pre-scan and post-scan hook in order to put comments into the file header (after all snapshot stuff and before the first data) and to the scan footer.

I think that now I understands better how Spec works in terms of the `comment` macro. Thanks!
The `comment` macro writes directly to the Spec file. The persistence is not necessary! Forgive me mixing things with the environment variables...
At the first glance, I think it should be also possible to eventually add this macro in the `pre-scan` hook to add `#C` lines after the snapshot and before the data. But I suggest to make some tests if the hook place is correctly located.

I think that the `comment` macro should be generic enough to accept other then Spec recorders. What do you think? In this case, the best would be to use the `DataHandler` class and its `addCustomData` method. I wonder how would the other recorders behave if we use them in this way? And how would the whole scan infrastructure behave if we do it within the `pre-scan` hook.

> #O, #J, #o, #j

For me the most resonable is to skip these for the moment in the file header. Let's hope this won't harm.

> I can try, but how should I contribute? Should I add the newfile macro directly to the default macros?

You have done it well in #777 so no answer here is necessary:) Let's continue discussing about `newfile` there. We will work intensivelly in the next days on reducing the PR queue...

**Comment by reszelaz** [comment]
Comming back to the scan file header and the initial request:

> As some analysis software requires a proper SPEC file header containing the motor and counter names 

In the above discussion we are close to not including the #O, #o, #J, #j - cause these may change in between the scans and at least myself I have no clear idea of what motors/counters we should put there.

@dschick do you still see benefits of having only a part of the spec file header i.e.

```
#F 2017-08-Schick-02
#E 1502445176
#D Fri Aug 11 11:52:56 2017
#C fourc  User = specadm
```

**Comment by teresanunez** [comment]
I think this can be closed or the title should be changed. The macro newfile is already implemented. I close it.
Feel free to open it, or I would say create a new one, if you miss something that it pointed out here.
