### ISSUE TITLE
'regscan' object has no attribute 'motors'

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#891]
I like to save the last used motor of any scan in the env for the pic, ce, etc, macros #890 
This works for a ascan but for regscan I get the error:
`'regscan' object has no attribute 'motors'`
what would be the best way to access the motor for all scans from within a macro?

**Comment by reszelaz** [comment]
Since scan macros just use the [Scan Framework](https://sardana-controls.org/devel/howto_macros/scan_framework.html) they are not obliged to expose the list of motors. As part of #784 I would just make it explicit that all scan macros using the framework must implement the *scan* property (name to be decided yet). Then the scan object has a public member `moveables`. I think this would be the best way. Until we decide the name of the said property I suggest to use _gScan. I think most of the scans follow this convention.

**Comment by dschick** [comment]
okay, I just saw that `regscan `is not inheriting from `aNscan `but just from `Macro`. Therefor `motors `is not defined but `movables `is directly definded within the macro.
As I understood it, I should use the scans `_gScan `object instead, altough the `movables `are also a property of the scan macro? Is that what you are saying?
Sorry, I am not really into the scan framework ...
