### ISSUE TITLE
Duplicate alias on same tango hosts

### ISSUE THREAD

**Issue by dschick** [sardana-org/sardana#998]
Hi everyone,

I just encountered a rather general problem, I fear:

I have two instances of sardana running on the same tango host. They both use different doors, pools, and macro servers.

However, as when I try to add a new motor/element to instance A which already exists with the same name on instance B, then I get the error that the tango alias already exists. 

Is there any possibility to get around that naming problem, as I would like to have the same names of similar motors in different sardana instances. 

Best 

Daniel

**Comment by cpascual** [comment]
I am no expert in this aspect, but AFAIK, this is a known hard limitation due to tango implementation of aliases as unique per database, and sardana relies on it in several key parts.

So,  if you really want to work around it you need to use multiple tango hosts. That is what we have at ALBA.

**Comment by guifrecuni** [comment]
Complementing what Carlos was saying, that's right, Sardana element "names" should be interpreted as "mnemonics", and as such, in the current implementation they refer to a specific device of the control system, which is based in TANGO devices, and the TANGO control system provides the feature of "alias" of a device which is unique (as the device is).

At ALBA we have _one_ TANGO_HOST per beamline and one TANGO_HOST for the Accelerators, so, as an example the very same "gap" motion of several slits within the same beamline are named: s1g, s2g, s3g, s4g, ... where 1-4 is the order along the beamline from source to sample. Then, another beamline could have same names.

When we do tests in the lab, we normally use incremental numbering so simulated motors may start from motor001 and end up with motor 023 for one sardana system and continue with motor024 for the next one. If I remember correctly, this is what should happen if you run sar_demo several times in different instances within the same TANGO_HOST.

**Comment by dschick** [comment]
Thanks for your replies.

But I can connect to multiple tango hosts from one sardana instance, right?

Are there plans to get around this issue?

I have the feeling that the need to run one tango hosts for every sardana
instance is maybe a bit overkill and requires extra administration,
especially in very small systems such as our lab.
Using numbers or namespaces for the alias could be also just a temporary
workaround for me.

But of course, I understand, that one would need to change the way sardana
saves the mnemonics: instead of using the tango alias, one would need some
extra Attribute. But I actually do not see a reason, why an alias in
Sardana needs to unique in Tango (Btw. I also don't see the point why a
tango alias needs to be unique in Tango, because there is the unique fqdn
in Tango, right?) the alias should only be unique per sardana instance.

Best

Daniel

Am Sa., 22. Dez. 2018, 10:36 hat Guifre Cuni <notifications@github.com>
geschrieben:

**Comment by reszelaz** [comment]
First of all Happy New Year to all :)

> But I can connect to multiple tango hosts from one sardana instance, right?

In Sardana you can, for example, connect Pools comming from different Tango hosts to a single MacroServer instance. We do that at Alba. Also you can write your macros which create devices from different Tango hosts.
 
> Are there plans to get around this issue?

This issue may be put on the table when the works on the configuration tool will start. This "big project" may try to isolate the persistance layer from the Tango database. But I can not foresee when this will start. Let's first complete the SEP2 and then we will try to define some further roadmap.
 
> I have the feeling that the need to run one tango hosts for every sardana
> instance is maybe a bit overkill and requires extra administration,
> especially in very small systems such as our lab.

I agree. Actually I don't know how this would work if several Tango database servers try to use the same mysql server. Maybe the best would be to ask on the Tango forum how to deal with that.

> But of course, I understand, that one would need to change the way sardana
> saves the mnemonics: instead of using the tango alias, one would need some
> extra Attribute.

Yes, I also had this idea in mind with a tiny difference: I would go for a property instead of an attribute. I would do that only for the devices which collide with already existing aliases or even only on an explicit request at the creation time.

However, this kind of implementation would need to be limited to use the Taurus Device extensions on the client side. The extension implementation would be responsible to look for the real Tango device based on the match between this property and a full name. Tango DeviceProxies would work only with the full names, of course only for the devices created in this special way. So, this solution won't be perfect and it may require quite some work...

>  But I actually do not see a reason, why an alias in
> Sardana needs to unique in Tango (Btw. I also don't see the point why a
> tango alias needs to be unique in Tango, because there is the unique fqdn
> in Tango, right?) the alias should only be unique per sardana instance.

The aliases must be unique in Tango cause they allow to refer to the real devices. If they won't be unique it won't be possible to find a unique device behind the alias.

**Comment by dschick** [comment]
> The aliases must be unique in Tango cause they allow to refer to the real devices. If they won't be unique it won't be possible to find a unique device behind the alias.

that is clear, when the alias is used to identify devices. I thought that the Taurus FQDN is used for that behind the scenes.

Anyhow, thanks alot for the detailed answer. I will try to set up additional Tango DBs for now.

Best

Daniel

**Comment by guifrecuni** [comment]
Hello,

I am still wondering why you have to take this (I agree with you) overkilling countermeasures, several TANGO DBs will come with more administrative tasks... and confusion to the users.

You stated above that you are talking about your lab which is a "small system", and I have no clue where in that system you have the name conflicts. Is it on physical motor names? Is it on specific experimental channels? is it for "pseudo elements"?

As I said, in the case of our accelerator there is a clear possible naming conflict since each ID has it's gap movement, we serve those motions in different Sardana TANGO servers, but within the same TANGO DBs, devices are unique and the aliases too, because there is a direct link between them, so, our approach was just preceed the "gap" motion with the "id identifier" and then, we get motions like "idxx_gap" for them.
At the beamlines, where there is just one TANGO DB, we could also get conflicts for "Z motions", "gap motions", or xbpm currents or calculated positions, we try to use instrument identifier as a prefix for those, because it is always linked to some physical instrument.

I'd say that it will have less impact if you go for this "prefix solution" than several TANGO DBs... (which at the end is also some kind of prefix at the FQDN)

Nevertheless, could you help me a little bit to understand your issue?
It is hard to me to imagine the root cause, why you may want the same name for different Pool Elements at the same time?

Doing an analogy of a file system, it seems that you would like to have f.txt being f1.txt, f2.txt, f3.txt depending on something.
The above prefix solution would be to simply use different filenames (obvious).
A part, there may be some alternatives:

1) Use the concept of symlink with MacroServer environment variables:
rm f.txt && ln -s f1.txt f.txt
do work
or
rm f.txt && ln -s f2.txt f.txt
do work
...
You could use the MacroServer environment variables to determine which is the actual element for that "shared alias among several elements" as we do for ActiveMntGrp which our scan framework relies on

2) Use the concept of renaming with "renameelem <element> <new_name>" macro:
mv f1.txt f.txt
do work
mv f.txt f1.txt
...

**Comment by dschick** [comment]
Hej @guifrecuni , thank you very much for getting back to this.

Actually, my situatuion is quite similar to the beamline example. I have, right now, two experiments in one lab, which share the same TANGO host.

At both experiments I have similar motors, like the `gap `at the beamline I have e.g. a motor called `delay `- so I do have two physical motors: one for each experiment. Now I would like to call this motor at both experiments/beamlines/Sardana instances simply `delay `and not `exp1_delay `and `exp2_delay`. This is simply out of convinience. As both experiments run in parallel have to use the motor `delay `at the same time accessing two different elements.

So it is clear, that for one experiment/beamline/Sardana instance every alias must be unique. But then Sardana can link this unique alias to any FQDN behind the scences and I would be fine.
One would just need to check the uniqueness of the alias per Sardana instance in Sardana itself, because one could not rely on the Tango implementation for the alias anymore.

I guess, what I do not have in mind is the possibility to include multiple pools from different Tango host to one Sardana instance, so this might be a showstopper here.

Hope I could make my point

**Comment by guifrecuni** [comment]
Ok, thanks for the clarification.
Regarding the fact that both experiments have to use the motor "delay" at the same time, are those experiments general scan macros or specific ones?
in the latter case, you could use the "symlink trick" by doing what the scan framework does to get the "active measurment group" element with defining an EnvironmentVariable ActiveDelayMotor in spock, and then something like this code inside the macro:
active_delay_motor =  self.getEnv("ActiveDelayMotor")
delay = self.getMotion(active_delay_motor) # or self.getMotor

In the first case, I'd suggest to write your own "scan wrapper macros" that do the same trick and call the generic ones: delay_ascan, or ascan_delay, etc...

Regarding the "multiple pools" option, even in multiple TANGO hosts, I'm affraid our Macroserver TANGO Device Server may not be prepared to handle the same alias internally, so, spock instances may not work neither...

**Comment by dschick** [comment]
with "experiment" I mean simply using SPOCK, so moving motors around and doing different scans with different motors. One of theses motors is then called e.g. `delay`

However, it seems, that your option with the symlink trick might be fine for me.
So I would create all elements with according prefixes and then in the actual sardana instances I can create such symlinks. Would the symlink also work with a simple
`mv delay 10`
if delay was a symlink?

**Comment by guifrecuni** [comment]
Hello, no, that would not be possible (as of today), when a user types "mv delay 10" internally there is a macro (in this case the standard mv one) that will do a "self.getMoveable with the delay _string_ provided by the user, and then, it's within the MacroServer's Elements attribute that this element should exist, and by the current design, element names are unique within a MacroServer, and by an extention, since it is based on TANGO aliases, unique within the whole TANGO database.
The analogy of the filesystem symlinks was to explain a possible workaround, which is not yet implemented if you want to use standard macros, but would be enough for specific ones. And it is not your case, since you want to do "mv delay 0.1" in one door and eventually "mv delay 0.2" in another one which should move another Pool motor.

I can imagine a "small" development where as a fallback for "not found elements", macros could also check if that name is a "symlink" using a specific Environment Variable (e.g. ElementSymLinks) to find the proper "real" element name.

**Comment by dschick** [comment]
alright, but just to come back to the original solution:
having multiple TangoDBs (in my case one for every Sardana Instance + one only for Hardware DS) should do the job or not?

**Comment by guifrecuni** [comment]
I have some news for you...
since you are using spock (ipython), what about this trick?
![image](https://user-images.githubusercontent.com/1969955/50683445-61561d00-1012-11e9-9725-95209d17456b.png)

**Comment by reszelaz** [comment]
@dschick if you finally go for the multiple Tango DBs this [documentation](https://tango-controls.readthedocs.io/en/latest/development/advanced/reference.html?highlight=mysql#the-database-and-controlled-access-server-mysql-user-mysql-password-mysql-host-and-mysql-database) may be helpful. Tango installation also provides a script for the creation of the database tables.

**Comment by dschick** [comment]
hej, I just created another tango DB on one of my Sardana host PCs and I am able to run Sardana on these new instance of Tango and still connect to tango DS from the old Tango DB host using the prefix in the namespace.

Although it is working well, it is also not so convinient to switch between the tango host, e.g. when using jive or to remember the host prefix all the time.

So I might use the prefixes in the aliases instead and then go for the ipython variables as symlinks.

Maybe I have to sleep a night over it

**Comment by reszelaz** [comment]
If I understand correctly you have now two different Tango databases. You moved one of your two Sardana systems, together with the underneeth non-Sardana Tango devices to the new Tango databse. Then you share the same PC for running the client applications from both Sardana systems?
In this case is the `TANGO_HOST` environment variable of any help to you?

**Comment by dschick** [comment]
I just try to rephrase what I did:

**before:**

### server ###
hosts the only Tango-DB in the lab/network
TANGO_HOST=server:10000
runs also a few Tango-DS for network attached hardware, e.g. Communication/TangoEpics

### client1 ###
runs Sardana instance for Experiment1
TANGO_HOST=server:10000

### client2 ###
runs Sardana instance for Experiment2
TANGO_HOST=server:10000

### several raspis ###
run Tango-DS for connected hardware with TANGO_HOST=server:10000

**now I have the following situation:**

### server ###
hosts the Tango-DB only for hardware Tango-DS
TANGO_HOST=server:10000
runs also a few Tango-DS for network attached hardware, e.g. Communication/TangoEpics

### client1 ###
hosts the Tango-DB for Sardana instance 1
runs Sardana instance for Experiment1
TANGO_HOST=client1:10000

### client2 ###
hosts the Tango-DB for Sardana instance 2
runs Sardana instance for Experiment2
TANGO_HOST=client2:10000

### several raspis ###
run Tango-DS for connected hardware with TANGO_HOST=server:10000

#############################

I can now also connect to all Tango-DS which run on the server via its prefix:
tango://server:10000/abc/xyz/1

**Comment by reszelaz** [comment]
Thanks! Now it is clear. Now, for each of the setups, you have devices distributed in two different Tango hosts (server and clientX), so for some cases you will need to use the full device name including the Tango host.

**Comment by dschick** [comment]
yep, your right. I have to use the tango host now for the full tango device names.

Thanks again for the help!

**Comment by reszelaz** [comment]
Hi @dschick,
Your idea is very good. I will need some time to estimate the effort. 

The first idea which comes to my mind, still very vague, is that we will need to _extend_ the Taurus Tango factory when creating `TangoDevice` objects. Maybe _extend_ the `TangoAuthority` (currently for the Taurus Tango scheme, this is simply a Tango Database) to be able to look for devices from a specific Pool/Sardana? I think we will need to define a specific scheme for that and make its use optional.

As you said the tricky part would be to make it as transparent as possible to the Sardana user. Of course, if someone decides to use PyTango directly, then there won't be possible to provide this transparency. Luckily in the Sardana code, we don't abuse from using PyTango directly.

**Comment by dschick** [comment]
Hi @reszelaz ,

this sounds like a good idea to me!
Defining such a scheme in the `sardana_custom_setiings` would be perfect.

If you prefix the alias in the TangoDB with the `Pool` name, you could run into troubles when connecting multiple Pools to a Door, as you would be able to create multiple elements with the same name in the Door.
But I think the same is already true if you add two `Pool`s from different `TANGO_HOST`s you could also have the same `alias` in one `Door`, right?

We are finally starting to migrate our first Tango/Sardana lab from Py2 to Py3 including new operating systems starting next week and in this we currently run three TangoDBs and are still in trouble with the alias issue, as we have like 5 `Doors`.
Maybe you could do an estimate how long it would take for this new feature and if it would be worth waiting for it?

Many thanks

Daniel
